-- ================================================================
-- 🏠 REAL ESTATE MANAGEMENT SYSTEM (FINAL COMPLETE SQL SCRIPT)
-- Author: Kartik Umesh Suchak
-- Purpose: Full Database + PL/SQL + Trigger setup for FastAPI + React
-- ================================================================

-- =====================
--  1️⃣ CLEANUP SECTION
-- =====================
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE property_logs CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE properties CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE agents CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =====================
--  2️⃣ TABLE CREATION
-- =====================

-- USERS TABLE
CREATE TABLE users (
    user_id NUMBER PRIMARY KEY,
    username VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255),
    full_name VARCHAR2(150),
    email VARCHAR2(150),
    phone VARCHAR2(20),
    role VARCHAR2(20),
    created_at DATE DEFAULT SYSDATE
);

-- AGENTS TABLE
CREATE TABLE agents (
    agent_id NUMBER PRIMARY KEY,
    user_id NUMBER REFERENCES users(user_id) ON DELETE CASCADE,
    license_no VARCHAR2(50),
    region VARCHAR2(100)
);

-- PROPERTIES TABLE
CREATE TABLE properties (
    property_id NUMBER PRIMARY KEY,
    agent_id NUMBER REFERENCES agents(agent_id) ON DELETE CASCADE,
    title VARCHAR2(150),
    description VARCHAR2(1000),
    city VARCHAR2(100),
    locality VARCHAR2(100),
    price NUMBER,
    property_type VARCHAR2(20),
    status VARCHAR2(20)
);

-- PROPERTY LOGS TABLE
CREATE TABLE property_logs (
    log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    property_id NUMBER,
    old_status VARCHAR2(50),
    new_status VARCHAR2(50),
    change_date DATE DEFAULT SYSDATE
);

-- =====================
--  3️⃣ SAMPLE DATA
-- =====================

INSERT INTO users VALUES (21, 'owen', 'hash', 'Owen Smith', 'owen@example.com', '9999999999', 'agent', SYSDATE);
INSERT INTO users VALUES (22, 'bob', 'hash', 'Bob Doe', 'bob@example.com', '8888888888', 'buyer', SYSDATE);
INSERT INTO users VALUES (23, 'alice', 'hash', 'Alice White', 'alice@example.com', '7777777777', 'buyer', SYSDATE);

INSERT INTO agents VALUES (24, 21, 'LIC123', 'West Zone');

INSERT INTO properties VALUES (25, 24, 'City Palace', 'Luxury house', 'Jaipur', 'Prime', 200000000, 'sale', 'sold');
INSERT INTO properties VALUES (26, 24, 'ABC Villa', 'Modern home', 'Mumbai', 'Prime', 100000, 'sale', 'sold');
INSERT INTO properties VALUES (27, 24, 'Lake View Apartment', 'Beautiful view', 'Nagpur', 'East', 5000000, 'rent', 'available');

COMMIT;

-- =====================
--  4️⃣ PL/SQL PROGRAMS
-- =====================

-- 🔹 PROCEDURE: Calculate Total Sales for Agent
CREATE OR REPLACE PROCEDURE calc_total_sales (
    p_agent_id IN NUMBER,
    p_total_sales OUT NUMBER
)
AS
BEGIN
    SELECT NVL(SUM(price), 0)
    INTO p_total_sales
    FROM properties
    WHERE agent_id = p_agent_id
      AND LOWER(status) = 'sold';
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_total_sales := 0;
END;
/

-- 🔹 FUNCTION: Get Total Commission (5% of sold properties)
CREATE OR REPLACE FUNCTION get_total_commission(p_agent_id IN NUMBER)
RETURN NUMBER
AS
    v_total_commission NUMBER;
BEGIN
    SELECT NVL(SUM(price * 0.05), 0)
    INTO v_total_commission
    FROM properties
    WHERE agent_id = p_agent_id
      AND LOWER(status) = 'sold';
    RETURN v_total_commission;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/

-- 🔹 CURSOR LOGIC DEMO: Available Properties by City
CREATE OR REPLACE PROCEDURE available_properties(p_city IN VARCHAR2)
AS
    CURSOR prop_cur IS
        SELECT property_id, title, price, status
        FROM properties
        WHERE LOWER(city) = LOWER(p_city)
          AND LOWER(status) = 'available';
    v_rec prop_cur%ROWTYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('Available properties in ' || p_city || ':');
    FOR v_rec IN prop_cur LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || v_rec.property_id || ' | ' || v_rec.title || ' | ₹' || v_rec.price || ' | ' || v_rec.status);
    END LOOP;
END;
/

-- 🔹 EXCEPTION HANDLING DEMO: Check Property Price
CREATE OR REPLACE PROCEDURE check_property(p_property_id IN NUMBER)
AS
    v_price NUMBER;
BEGIN
    SELECT price INTO v_price
    FROM properties
    WHERE property_id = p_property_id;

    DBMS_OUTPUT.PUT_LINE('✅ Property ID ' || p_property_id || ' Price: ₹' || v_price);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('❌ Property with ID ' || p_property_id || ' not found.');
END;
/

-- 🔹 TRIGGER: Log Property Status Changes
CREATE OR REPLACE TRIGGER trg_property_status_log
AFTER UPDATE OF status ON properties
FOR EACH ROW
WHEN (OLD.status IS DISTINCT FROM NEW.status)
BEGIN
    INSERT INTO property_logs (property_id, old_status, new_status, change_date)
    VALUES (:OLD.property_id, :OLD.status, :NEW.status, SYSDATE);
END;
/

COMMIT;

-- =====================
--  5️⃣ TESTING SECTION
-- =====================

-- 🧾 Test Total Sales
VARIABLE result NUMBER;
EXEC calc_total_sales(24, :result);
PRINT result;

-- 🧾 Test Total Commission
SELECT get_total_commission(24) AS total_unpaid_commission FROM dual;

-- 🧾 Test Available Properties
SET SERVEROUTPUT ON;
EXEC available_properties('Nagpur');

-- 🧾 Test Check Property Price
EXEC check_property(26);

-- 🧾 View Property Logs
SELECT * FROM property_logs;

-- ================================================================
